import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"; // Pastikan baris ini ada

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AI Image Generator",
  description: "Generated by Ruang Riung and Partner Coding",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<body className={`${inter.className} bg-red-500`}>{children}</body>
    </html>
  );
}