import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import AuthProvider from '@/components/AuthProvider';
import Footer from '@/components/Footer'; // Impor Footer

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AI Image Generator",
  description: "Generated by Ruang Riung and Partner Coding",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-light-bg`}>
        <AuthProvider>
          {/* Main content tetap di sini, tetapi body akan flex column */}
          <div className="flex flex-col min-h-screen">
            <main className="flex-grow">
              {children}
            </main>
            {/* Tambahkan Footer di sini */}
            <Footer />
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}