export const DEFAULT_ADSENSE_PUBLISHER_ID = 'ca-pub-1439044724518446';

export const ADSENSE_PUBLISHER_ID =
  process.env.NEXT_PUBLIC_ADSENSE_PUBLISHER_ID ?? DEFAULT_ADSENSE_PUBLISHER_ID;

export const ADSENSE_META_ACCOUNT =
  process.env.NEXT_PUBLIC_ADSENSE_META_ACCOUNT ?? ADSENSE_PUBLISHER_ID;
