import type { ModerationItem } from './types';

export const moderationStorageKey = 'ruangriung_admin_moderation_queue_v1';

export const initialModerationItems: ModerationItem[] = [
  {
    id: 'prompt-2024-07-21-001',
    type: 'prompt',
    title: 'Poster Festival Kuliner Nusantara',
    submittedBy: 'Siti Marlina',
    submittedAt: '2024-07-21T09:24:00+07:00',
    status: 'pending',
    priority: 'high',
    channel: 'Formulir Prompt Publik',
    contactEmail: 'siti.marlina@example.com',
    notes: 'Perlu cek ulang hak cipta foto referensi dan ejaan kota pada deskripsi acara.',
    tags: ['kuliner', 'poster', 'event komunitas'],
  },
  {
    id: 'profile-2024-07-19-003',
    type: 'profile',
    title: 'Profil Konten Kreator - Rahmat Wijaya',
    submittedBy: 'Rahmat Wijaya',
    submittedAt: '2024-07-19T14:10:00+07:00',
    status: 'in_review',
    priority: 'medium',
    channel: 'Formulir Direktori Kreator',
    contactEmail: 'rahmat.wijaya@example.com',
    contactWhatsapp: '+6281234567890',
    notes: 'Butuh verifikasi portofolio video YouTube serta konfirmasi hak penggunaan logo brand.',
    tags: ['video', 'edukasi bisnis'],
    assignee: 'Nadifa Family',
    lastUpdated: '2024-07-20T09:05:00+07:00',
  },
  {
    id: 'umkm-2024-07-18-002',
    type: 'umkm',
    title: 'UMKM - Dapur Rempah Mbak Yani',
    submittedBy: 'Yani Pratiwi',
    submittedAt: '2024-07-18T19:45:00+07:00',
    status: 'pending',
    priority: 'medium',
    channel: 'Formulir Direktori UMKM',
    contactEmail: 'dapurrempah@example.com',
    contactWhatsapp: '+6282276543210',
    notes: 'Lampiran foto produk masih blur, minta unggahan ulang resolusi tinggi.',
    tags: ['kuliner', 'frozen food'],
  },
  {
    id: 'prompt-2024-07-16-004',
    type: 'prompt',
    title: 'Storyboard Video Peluncuran Produk Eco Laundry',
    submittedBy: 'Eco Laundry Studio',
    submittedAt: '2024-07-16T11:30:00+07:00',
    status: 'approved',
    priority: 'low',
    channel: 'Email Manual',
    contactEmail: 'partnership@ecolaundry.id',
    relatedLink: 'https://drive.google.com/file/d/abc123',
    notes: 'Sudah disunting minor oleh tim editorial, siap dijadwalkan untuk publikasi.',
    tags: ['video prompt', 'product launch'],
    assignee: 'Koko Ajeeb',
    lastUpdated: '2024-07-18T08:20:00+07:00',
  },
  {
    id: 'profile-2024-07-15-001',
    type: 'profile',
    title: 'Profil Konten Kreator - Dinda Larasati',
    submittedBy: 'Dinda Larasati',
    submittedAt: '2024-07-15T16:55:00+07:00',
    status: 'rejected',
    priority: 'low',
    channel: 'Formulir Direktori Kreator',
    contactEmail: 'dinda.larasati@example.com',
    notes: 'Konten tidak sesuai dengan fokus komunitas; sarankan revisi dengan pilar konten edukasi UMKM.',
    tags: ['fashion', 'lifestyle'],
    assignee: 'Famii',
    lastUpdated: '2024-07-17T10:42:00+07:00',
  },
  {
    id: 'umkm-2024-07-12-005',
    type: 'umkm',
    title: 'UMKM - Kopi Seduh Harian',
    submittedBy: 'Andi Herlambang',
    submittedAt: '2024-07-12T08:18:00+07:00',
    status: 'in_review',
    priority: 'high',
    channel: 'WhatsApp Community Manager',
    contactEmail: 'kopiseduh@example.com',
    contactWhatsapp: '+6281399988776',
    notes: 'Sudah diverifikasi alamat gerai. Tinggal cek ulang deskripsi signature menu.',
    tags: ['kopi', 'minuman'],
    assignee: 'Yogi Arfianto',
    lastUpdated: '2024-07-19T21:15:00+07:00',
  },
];
